def calculateresult(first_number, operation, second_number):
    if operation == '+':
        return first_number + second_number
    if operation == '-':
        return first_number - second_number
    if operation == '*':
        return first_number * second_number
    if operation == '/':
        return first_number / second_number